// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAItCm_4Rz834dfemZ7hNEc3oPr0mCc4Sc',
    appId: '1:255533361884:web:3a58319c9e91bc6dfde219',
    messagingSenderId: '255533361884',
    projectId: 'face-auth-flutter-80dac',
    authDomain: 'face-auth-flutter-80dac.firebaseapp.com',
    storageBucket: 'face-auth-flutter-80dac.appspot.com',
    measurementId: 'G-01M1LKC3EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZlUTZyoSyZq4m5Fs-qOycznIzQTtuP6c',
    appId: '1:255533361884:android:76c7f5e9b8bc8be1fde219',
    messagingSenderId: '255533361884',
    projectId: 'face-auth-flutter-80dac',
    storageBucket: 'face-auth-flutter-80dac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWHZh7ij22BCitsSWA-RqDi1lG_K2hZEU',
    appId: '1:255533361884:ios:7fc306c9f078ec99fde219',
    messagingSenderId: '255533361884',
    projectId: 'face-auth-flutter-80dac',
    storageBucket: 'face-auth-flutter-80dac.appspot.com',
    iosBundleId: 'com.example.faceAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWHZh7ij22BCitsSWA-RqDi1lG_K2hZEU',
    appId: '1:255533361884:ios:9ed6f6351d24b358fde219',
    messagingSenderId: '255533361884',
    projectId: 'face-auth-flutter-80dac',
    storageBucket: 'face-auth-flutter-80dac.appspot.com',
    iosBundleId: 'com.example.faceAuth.RunnerTests',
  );
}
